services:
  - type: web
    name: case-search-rag
    env: docker
    plan: free
    region: singapore
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 3000
      - key: GCP_SERVICE_ACCOUNT_JSON
        sync: false
      - key: GOOGLE_CLOUD_PROJECT
        value: eco-seeker-458712-i8
      - key: GOOGLE_CLOUD_LOCATION
        value: us-central1
      - key: CLOUDFLARE_R2_URL
        sync: false
